version: "3"
services:
  jenkins:
    build: 
      context: .
    image: jenkins-jdk11-arm64:2.249.1
    ports:
      - "8080:8080"
    environment:
      - JENKINS_HOME=/home/jenkins/data
    volumes:
      - /data/jenkins:/home/jenkins/data
    restart: always
